<a href="https://colab.research.google.com/github/vansh2447/vansh2447/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np
arr=np.array([[0,1,2,3],[4,5,6,7]])
print(arr)
print(type(arr))
print(arr.shape)

[[0 1 2 3]
 [4 5 6 7]]
<class 'numpy.ndarray'>
(2, 4)


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)
print(arr.reshape(8,))

[ 6  8 10 12]
[0 1 2 3 4 5 6 7]
